### ISSUE TITLE
Unify name style from snake_case to camelCase : MAJOR VERSION

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#112]
Need to unify writing style.
watch out : as we will make incompatible changes in public API, we must switch to a new Major version

**Comment by jul** [comment]
Why not use science to decide ?
https://www.researchgate.net/publication/224159770_An_Eye_Tracking_Study_on_camelCase_and_under_score_Identifier_Styles

Very sumed up : it does not matter for experienced developper.
But for less exeperienced ones choosing snake_case increases the speed of accurate lecture.
Let's be nice to the newcomers  :)

**Comment by dascritch** [comment]
We start to roll up a new version, as I significantly changed Element.CPU.remove_highlights_points() , which is a public method.
Next planned change in public pethod :  Element.CPU.add_point()  from (plane_name, cuepoint, point_name,..) to more logical (plane_name, point_name, cuepoint,..)

**Comment by dascritch** [comment]
pfff.... tired -_-

**Comment by dascritch** [comment]
- [ ] convert
- [ ] cpu_*.class
- [ ] defaults_*
- [ ] document_cpu
- [ ] element_cpu
- [ ] finger_manager
- [ ] index
- [ ] media_element
- [ ] translate_vtt
- [ ] trigger
- [ ] utils
- [ ] private methods

**Comment by dascritch** [comment]
- [ ] convert
- [ ]
