### ISSUE TITLE
Example of React integration

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#120]
May be React developers may be interested in this component. We need to show an example and document caveats.

**Comment by dascritch** [comment]
Part needed here <https://fr.reactjs.org/docs/web-components.html>

The cpu-audio.js must be loaded from the HTML template, due to compilation.

```html
    <script src="%PUBLIC_URL%/cpu-audio.js" async></script>
```

**Comment by scombat** [comment]
It seems to be working fine like this :

```
import React, { useEffect } from 'react';

export const Audio = () => {
  useEffect(() => import("../../public/vendors/cpu-audio.min.js"), []);

  return (
    <div>
      <cpu-audio>
        <audio controls src='/blank.mp3'></audio>
      </cpu-audio>
    </div>
  )
};
```

See my example (quick & dirty) [repository](https://github.com/scombat/react-cpu-audio) and specific [source code](https://github.com/scombat/react-cpu-audio/blob/main/Components/atoms/audio.js)
You can try it with a `yarn && yarn install && yarn dev`

**Comment by dascritch** [comment]
WOOOOW !!!! 
Don't you want to be correctly credited in it ? doing a `examples/Call_from_Rreact.jsx` ?

Thank you soooo much !

**Comment by dascritch** [comment]
Wonderful work from @scombat ! I think it needn't to create a `<div>` , simple `<>` globing must be enough

**Comment by dascritch** [comment]
A very fast placeholder, if @scombat want to complete it
