### ISSUE TITLE
Being able to not include global.css on host page

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#181]
Add an attribute option in the calling script for cpu-audio to not include the global cs definition.
We may need to not include it to avoid confusions for the integrations

**Comment by Abirham24** [comment]
Hello, can work on this issue ?

**Comment by Abirham24** [comment]
Hello, can I work on this issue?

**Comment by dascritch** [comment]
Hello @Abirham24 !
Yes ! you're welcome !

I've locked the master branch, so create a feature one. I'm also here to help you.
There is a lot of questions as : how to detect when the integrated webpage doesn't want to have global.css inserted ? As an attribute to the `<script>` tag ? or to the `<head>` ? 

May be you've got a elegant and creative way to do it !

**Comment by Abirham24** [comment]
Hello @dascritch, Thank you for your response. I am very interested to work on this issue.  Could you help me with how to start with it or send me any guidance links hence I am new to the open source community.

**Comment by dascritch** [comment]
Most of the useful informations are in https://github.com/dascritch/cpu-audio/blob/master/CONTRIBUTING.md .
Code is done in vanilla JS, ECMA 2022, CSS grade is v4. We use english for function, variables and comments. Autodoc is mandatory for any functions, don't hesitate to comment what you do.  And think about minimal code to start.

Each time you want to check your code, run `./make.sh --clean --all-themes --test --index`  to check that something didn't break elsewhere. Test covering is not exhaustive, but I wish to improve it.

**Comment by dascritch** [comment]
Sorry. I should remove the “good first issue” tag for this story, as the file is included directly and done via the bash script `make.sh` in the `_build_template` function. I'll take it later.

Better first issue is perhaps #60 where you have to modify the `hashchange` event behaviour

**Comment by dascritch** [comment]
May be the easier way to achieve it would be to do alternate builds, with the global.css merged in the hosted css ?
Needs some rework

**Comment by dascritch** [comment]
Woops ! NO ! It's easy to do it ! 
@Abirham24  , you have to call `insert_style()` from `main()` on a conditional

**Comment by dascritch** [comment]
@Abirham24 , are you on it ? I have to do some changes

**Comment by dascritch** [comment]
@Abirham24 We now have a proper method to pre-parameter global settings

**Comment by dascritch** [comment]
No answer, i'll take it
