### ISSUE TITLE
Test and document CSP issues

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#74]
- Are ShadowDOM in WebComponents also impacted against inline style ?
- Do we need specially permissive CSP rules ?

Most of tests i saw was about polyfill js, emulating shadowDom

**Comment by nico3333fr** [comment]
Gnnniiiiii, between autorizations for polyfills, components... this will be complicated.

**Comment by dascritch** [comment]
I will ignore polyfill. We aren't need them anymore (except importing html into html)

**Comment by dascritch** [comment]
Let's ignore completely : we use standard JS import, so no need.
